pages:
  # key is the dirname of pages in src/pages
  home:
    # 首页配置
    zh-cn:
      title: 'Wuhan2020'
      keywords: '官网,首页'
      description: 'Wuhan2020官网'
    # home config
    en-us:
      title: 'Wuhan2020'
      keywords: 'Official,Wuhan2020'
      description: 'Wuhan2020 Official Website'
  community:
    # 社区页配置
    zh-cn:
      title: '社区'
      keywords: 'Wuhan2020,社区'
      description: 'Wuhan2020社区'
    # community page config
    en-us:
      title: 'Community'
      keywords: 'Seata,Community'
      description: 'Seata Community'
  blog:
    # 博客列表页配置
    zh-cn:
      title: '博客'
      keywords: 'Wuhan2020,博客'
      description: 'Wuhan2020 博客'
    # blog list page config
    en-us:
      title: 'Blog'
      keywords: 'Wuhan2020,Blog'
      description: 'Wuhan2020 Blog'
  project:
    # 项目列表页配置
    zh-cn:
      title: '项目列表'
      keywords: 'Wuhan2020,项目列表'
      description: 'Wuhan2020 项目列表'
    # project list page config
    en-us:
      title: 'Projects'
      keywords: 'Wuhan2020, Projects'
      description: 'Wuhan2020 projects'
  certification:
    # apply the certification
    zh-cn:
      title: 'certification'
      keywords: 'certification'
      description: 'certification'
    en-us:
      title: 'certification'
      keywords: 'certification'
      description: 'certification'